//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CateringOrder()
        {
            this.CateringOrderDetail = new HashSet<CateringOrderDetail>();
        }
    
        public int ID { get; set; }
        public int Volume { get; set; }
        public int UserID { get; set; }
        public int SeatID { get; set; }
        public int CompletionState { get; set; }
        public byte[] LastChange { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CateringOrderDetail> CateringOrderDetail { get; set; }
    }
}
