//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringOrderDetail
    {
        public int ID { get; set; }
        public int CateringOrderID { get; set; }
        public int CateringProductID { get; set; }
        public string Attributes { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CateringOrder CateringOrder { get; set; }
        public virtual CateringProduct CateringProduct { get; set; }
    }
}
