//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CateringProduct()
        {
            this.CateringOrderDetail = new HashSet<CateringOrderDetail>();
            this.CateringProductAttributeRelation = new HashSet<CateringProductAttributeRelation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.Guid ImageContainerID { get; set; }
        public decimal Price { get; set; }
        public bool SingleChoice { get; set; }
        public bool IsActive { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CateringOrderDetail> CateringOrderDetail { get; set; }
        public virtual ImageContainer ImageContainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CateringProductAttributeRelation> CateringProductAttributeRelation { get; set; }
    }
}
