//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CateringOrder()
        {
            this.CateringOrderDetail = new HashSet<CateringOrderDetail>();
        }
    
        public int ID { get; set; }
        public int EventID { get; set; }
        public int UserID { get; set; }
        public int SeatID { get; set; }
        public string Note { get; set; }
        public System.DateTime Registered { get; set; }
        public int OrderState { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CateringOrderDetail> CateringOrderDetail { get; set; }
    }
}
