//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringOrderDetail
    {
        public int ID { get; set; }
        public int CateringOrderID { get; set; }
        public int CateringProductID { get; set; }
        public string Attributes { get; set; }
        public byte[] RowVersion { get; set; }
        public int Amount { get; set; }
    
        public virtual CateringOrder CateringOrder { get; set; }
        public virtual CateringProduct CateringProduct { get; set; }
    }
}
