//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeSet
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CateringOrder { get; set; }
        public Nullable<System.DateTime> CateringProduct { get; set; }
        public Nullable<System.DateTime> CateringOrderDetail { get; set; }
        public Nullable<System.DateTime> Chat { get; set; }
        public Nullable<System.DateTime> Logs { get; set; }
        public Nullable<System.DateTime> Partner { get; set; }
        public Nullable<System.DateTime> PartnerPack { get; set; }
        public Nullable<System.DateTime> Seat { get; set; }
        public Nullable<System.DateTime> Settings { get; set; }
        public Nullable<System.DateTime> Tournament { get; set; }
        public Nullable<System.DateTime> TournamentGame { get; set; }
        public Nullable<System.DateTime> TournamentTeam { get; set; }
        public Nullable<System.DateTime> TournamentParticipant { get; set; }
        public Nullable<System.DateTime> User { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
