//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeSet
    {
        public int ID { get; set; }
        public System.DateTime CateringOrder { get; set; }
        public System.DateTime CateringProducts { get; set; }
        public System.DateTime Chat { get; set; }
        public System.DateTime Logs { get; set; }
        public System.DateTime Partner { get; set; }
        public System.DateTime PartnerPack { get; set; }
        public System.DateTime Seat { get; set; }
        public System.DateTime Settings { get; set; }
        public System.DateTime Tournament { get; set; }
        public System.DateTime TournamentGame { get; set; }
        public System.DateTime TournamentTeam { get; set; }
        public System.DateTime TournamentParticipant { get; set; }
        public System.DateTime User { get; set; }
        public System.DateTime RowVersion { get; set; }
    }
}
