//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeSet
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CateringProduct { get; set; }
        public Nullable<System.DateTime> CateringOrder { get; set; }
        public Nullable<System.DateTime> CateringOrderDetail { get; set; }
        public Nullable<System.DateTime> CateringProductAttribute { get; set; }
        public Nullable<System.DateTime> CateringProductAttributeRelation { get; set; }
        public Nullable<System.DateTime> Event { get; set; }
        public Nullable<System.DateTime> EventType { get; set; }
        public Nullable<System.DateTime> FaqQuestion { get; set; }
        public Nullable<System.DateTime> FaqCategory { get; set; }
        public Nullable<System.DateTime> Logs { get; set; }
        public Nullable<System.DateTime> Partner { get; set; }
        public Nullable<System.DateTime> PartnerDisplay { get; set; }
        public Nullable<System.DateTime> PartnerDisplayRelation { get; set; }
        public Nullable<System.DateTime> PartnerPack { get; set; }
        public Nullable<System.DateTime> Seat { get; set; }
        public Nullable<System.DateTime> SeatTransferLog { get; set; }
        public Nullable<System.DateTime> Tournament { get; set; }
        public Nullable<System.DateTime> TournamentGame { get; set; }
        public Nullable<System.DateTime> TournamentTeam { get; set; }
        public Nullable<System.DateTime> TournamentParticipant { get; set; }
        public Nullable<System.DateTime> TournamentWinner { get; set; }
        public Nullable<System.DateTime> TournamentWinnerPlayer { get; set; }
        public Nullable<System.DateTime> TournamentWinnerTeam { get; set; }
        public Nullable<System.DateTime> User { get; set; }
        public Nullable<System.DateTime> UserTask { get; set; }
        public Nullable<System.DateTime> UserTaskRelation { get; set; }
        public Nullable<System.DateTime> UserRole { get; set; }
        public Nullable<System.DateTime> UserRoleRelation { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
