//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.CateringOrder = new HashSet<CateringOrder>();
            this.Seat = new HashSet<Seat>();
            this.Tournament = new HashSet<Tournament>();
        }
    
        public int ID { get; set; }
        public int EventTypeID { get; set; }
        public int Volume { get; set; }
        public Nullable<System.Guid> ImageContainerID { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public double ReservationCost { get; set; }
        public int IsActiveReservation { get; set; }
        public bool IsActiveCatering { get; set; }
        public bool IsActiveFeedback { get; set; }
        public bool IsPrivate { get; set; }
        public string FeedbackLink { get; set; }
        public string District { get; set; }
        public string Street { get; set; }
        public string Housenumber { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CateringOrder> CateringOrder { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual ImageContainer ImageContainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tournament> Tournament { get; set; }
    }
}
