//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string SQLTable { get; set; }
        public string SQLActionType { get; set; }
        public string SQLQuery { get; set; }
        public string ModelBefore { get; set; }
        public string ModelAfter { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual User User { get; set; }
    }
}
