//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string SQLTable { get; set; }
        public string SQLActionType { get; set; }
        public string SQLQuery { get; set; }
        public string ModelBefore { get; set; }
        public string ModelAfter { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual User User { get; set; }
    }
}
