//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CateringOrder> CateringOrder { get; set; }
        public virtual DbSet<CateringOrderDetail> CateringOrderDetail { get; set; }
        public virtual DbSet<CateringProduct> CateringProduct { get; set; }
        public virtual DbSet<CateringProductAttribute> CateringProductAttribute { get; set; }
        public virtual DbSet<CateringProductAttributeRelation> CateringProductAttributeRelation { get; set; }
        public virtual DbSet<ChangeSet> ChangeSet { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<FaqCategory> FaqCategory { get; set; }
        public virtual DbSet<FaqQuestion> FaqQuestion { get; set; }
        public virtual DbSet<ImageContainer> ImageContainer { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCategory> NewsCategory { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<PartnerDisplay> PartnerDisplay { get; set; }
        public virtual DbSet<PartnerDisplayRelation> PartnerDisplayRelation { get; set; }
        public virtual DbSet<PartnerPack> PartnerPack { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<SeatTransferLog> SeatTransferLog { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<TournamentGame> TournamentGame { get; set; }
        public virtual DbSet<TournamentParticipant> TournamentParticipant { get; set; }
        public virtual DbSet<TournamentTeam> TournamentTeam { get; set; }
        public virtual DbSet<TournamentTeamParticipant> TournamentTeamParticipant { get; set; }
        public virtual DbSet<TournamentWinner> TournamentWinner { get; set; }
        public virtual DbSet<TournamentWinnerPlayer> TournamentWinnerPlayer { get; set; }
        public virtual DbSet<TournamentWinnerTeam> TournamentWinnerTeam { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPrivilege> UserPrivilege { get; set; }
        public virtual DbSet<UserPrivilegeRelation> UserPrivilegeRelation { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRolePrivilegeRelation> UserRolePrivilegeRelation { get; set; }
        public virtual DbSet<UserTask> UserTask { get; set; }
        public virtual DbSet<UserTaskRelation> UserTaskRelation { get; set; }
    }
}
