//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Tournament = new HashSet<Tournament>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public string ImageAlt { get; set; }
        public int PartnerPackID { get; set; }
        public bool IsActive { get; set; }
        public int Position { get; set; }
        public int ClickCount { get; set; }
        public byte[] LastChange { get; set; }
    
        public virtual PartnerPack PartnerPack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tournament> Tournament { get; set; }
    }
}
