//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat()
        {
            this.CateringOrder = new HashSet<CateringOrder>();
            this.SeatTransferLog = new HashSet<SeatTransferLog>();
        }
    
        public int ID { get; set; }
        public int SeatNumber { get; set; }
        public int EventID { get; set; }
        public int UserID { get; set; }
        public int State { get; set; }
        public string Description { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public bool Payed { get; set; }
        public Nullable<int> TransferUserID { get; set; }
        public bool IsActive { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CateringOrder> CateringOrder { get; set; }
        public virtual Event Event { get; set; }
        public virtual User TransferUser { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatTransferLog> SeatTransferLog { get; set; }
    }
}
