//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.NetConnect.data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentWinner
    {
        public int ID { get; set; }
        public int TournamentID { get; set; }
        public System.Guid ImageContainerID { get; set; }
        public int Placement { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ImageContainer ImageContainer { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual TournamentWinnerPlayer TournamentWinnerPlayer { get; set; }
        public virtual TournamentWinnerTeam TournamentWinnerTeam { get; set; }
    }
}
